package server;

public enum Codigos {
     CERRAR_CHAT,   // 504
     DESCONECTAR,  // 503
     ACTIVAR_ESCUCHA,  // 300
     DESACTIVAR_ESCUCHA,  // 301
     INICIAR_CHAT,  // 350
     NUEVO_MENSAJE, // 351
     USERNAME_REPETIDO, // 409
     OK,   // 200
     NO_ENCONTRADO, // 404
     ACTUALIZAR_LISTA_USUARIOS,
     NADIE_SOLICITO,
     RESINCRONIZAR,
     ACTIVAR_SECUNDARIO
}
